### ISSUE TITLE
MIN_PHP_VERSION is 5.5

### ISSUE THREAD

**Issue by normance** [TextControl/txtextcontrol-reportingcloud-php#6]
Hi,

  We are using livedocx with ZF 1.12.20 and PHP 5.4. I know this it's becoming obsolete but we are not living in a perfect world :) 
  You are phasing out livedocx, but upgrading from ZF1 and APC which are not compliant with php 5.5 (not 100% sure about ZF1) is out of reach for just switching wrapper from livedocx to reportingCloud.

  What are the classes or statements that prevent your wrapper to be PHP 5.4 compliant ?

Thanks in advance
Regards

**Comment by jonathanmaron** [comment]
Hello there

The ReportingCloud PHP wrapper depends upon Guzzle HTTP client, which itself has a PHP version requirement of 5.5 or better. 

You can use ReportingCloud in your PHP 5.4 project directly via its Web API and JSON without the wrapper. You just need to use an earlier version of Guzzle, or an other HTTP client entirely that runs in your environment. 

If you need any more assistance, please let me know. 

With kindest regards 

Jonathan Maron
